spring:
  application:
    name: hexagonal
  data:
    mongodb:
      uri: mongodb://localhost:27017/hexagonal

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger
  openapi:
    info:
      title: API Centros - Borja Hexagonal
      version: 1.0.0